---
kind: pipeline
type: docker
name: default

steps:
- name: build
  # this is an image created manually using
  # https://github.com/yarnpkg/yarn/blob/master/Dockerfile.dev
  image: yarn
  pull: never
  commands:
  - yarn install
  - yarn jest
  - yarn build
  environment:
    LANG: "C.UTF-8"
- name: deploy
  image: drillster/drone-rsync
  trigger:
    branch:
    - master
  settings:
    hosts: [ "vps608404.ovh.net" ]
    user: xpath
    source: dist/
    target: /home/xpath/xpath/
    recursive: true
    delete: true
    key:
      from_secret: xpath_ssh_key
  when:
    branch:
    - main
    status:
    - success
